apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-frontend-reader
  namespace: default
subjects:
  - kind: ServiceAccount
    name: frontend-sa
    namespace: default
roleRef:
  kind: Role
  name: frontend-reader
  apiGroup: rbac.authorization.k8s.io
