apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /home/adeel/Micronews-k8s/data/mongo-backups