apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarizer
  template:
    metadata:
      labels:
        app: summarizer
    spec:
      serviceAccountName: summarizer-sa
      containers:
      - name: summarizer
        image: adeel2k01/summarizer:latest
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu:    "250m"
            memory: "128Mi"
          limits:
            cpu:    "500m"
            memory: "256Mi"
